config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#show'
  get '/auth/:provider/callback', to: 'sessions#create'

  resource :session, only: [:destroy]
  resources :orders, only: [:index, :new, :create]
  resources :imports, only: [:new, :create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user

  def user?
    user.present?
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  validates :date, presence: true
  validates :total, presence: true, numericality: { greater_than: 0, less_than: 999999.99 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :orders

  encrypts :access_token, :refresh_token

  def self.find_or_create_by_auth(auth)
    user = find_or_create_by(uid: auth['uid'])

    user.update!(
      first_name: auth.info.first_name,
      last_name: auth.info.last_name,
      login: auth.info.login,
      email: auth.info.email,
      access_token: auth.credentials.token,
      refresh_token: auth.credentials.refresh_token
    )

    user
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate

  private

  def authenticate
    Current.user = User.find_by(id: session[:user_id])
  end

  def require_user
    redirect_to root_path unless Current.user?
  end

  def require_no_user
    redirect_to root_path if Current.user?
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def show; end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def new
  end

  def create
    RefreshTokensJob.perform_now(Current.user)
    forms = FetchCheckoutFormsJob.perform_now(Current.user)

    ActiveRecord::Base.transaction do
      forms.each do |form|
        order = Current.user.orders.find_or_initialize_by(uid: form['id'])
        order.update!(
          date: form.dig('payment', 'finishedAt'),
          total: form.dig('payment', 'paidAmount', 'amount'),
          description: form.dig('lineItems').map { |line_item| line_item.dig('offer', 'name') }.join(', ')
        )
      end
    end

    redirect_to orders_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_user

  def index
    @orders = Current.user.orders
  end

  def new
    @order = Current.user.orders.build
  end

  def create
    @order = Current.user.orders.build(order_params)

    if @order.save
      redirect_to orders_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def order_params
    params.require(:order).permit(:date, :total, :description)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_by_auth(auth_hash)
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/show.html.erb
test

<%= Current.user.try(:email) %>

app/views/imports/new.html.erb
<h3>New Import</h3>

<%= button_to 'Import', imports_path, method: :post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <%= link_to 'Home', root_path %>
        <%= link_to 'Orders', orders_path %>
        <%= link_to 'Imports', new_import_path %>
      </nav>
      <h1>Onion</h1>
      <p>
        <% if Current.user? %>
          <%= Current.user.email %>
          <%= button_to 'Logout', session_path, method: 'delete' if Current.user? %>
        <% else %>
          <%= button_to 'Login', '/auth/allegro', data: { turbo: 'false' } unless Current.user? %>
        <% end %>
      </p>
    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/orders/index.html.erb
<h2>
  Orders
</h2>

<%= link_to "New Order", new_order_path %>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Opis</th>
      <th>Kwota</th>
    </tr>
  </thead>
  <tbody>
    <% if @orders.empty? %>
      <tr>
        <td colspan="3">Brak pozycji</td>
      </tr>
    <% else %>
      <% @orders.each do |order| %>
        <tr>
          <td><%= time_tag(order.date) %></td>
          <td><%= order.description %></td>
          <td><%= number_to_currency(order.total) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2">Suma</td>
      <td><%= number_to_currency(@orders.sum(:total)) %></td>
    </tr>
  </tfoot>
</table>

app/views/orders/new.html.erb
<h3>New Order</h3>

<%= form_with model: @order do |form| %>
  <p>
    <%= form.label :date %><br>
    <%= form.date_field :date %><br>
    <%= form.object.errors[:date].join(', ') %>
  </p>

  <p>
    <%= form.label :total %><br>
    <%= form.number_field :total, step: '0.01' %><br>
    <%= form.object.errors[:total].join(', ') %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %><br>
    <%= form.object.errors[:description].join(', ') %>
  </p>

  <p>
    <%= button_tag "Submit", type: "submit" %>
  </p>
<% end %>